language: python

cache: pip

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - wget -c https://goo.gl/ZzKHFv -O - | tar -xvJ -C /tmp/
  - PATH="/tmp/shellcheck-latest:$PATH"

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install --no-deps -r req_nodeps.txt
  - travis_retry pip install flake8
  - pip list --format=columns --outdated

script:
  - flake8 --statistics shipyard.py convoy/*.py
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then flake8 --statistics cascade/*.py cargo/*.py heimdall/*.py; fi
  - shellcheck ./*.sh cargo/*.sh cascade/*.sh docker/*.sh scripts/*.sh
