version: '{branch}-{build}'

clone_depth: 5

cache:
- '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7"
    PYTHON_ARCH: "64"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7"
    PYTHON_ARCH: "64"

init:
- echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
- "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- where pip
- "%PYTHON%\\python.exe -m pip install --upgrade --user pip"
- pip install --upgrade setuptools wheel
- pip install -r requirements.txt
- pip install --no-deps -r req_nodeps.txt
- pip install flake8
- pip list --format=columns --outdated

build: off

test_script:
- flake8 --statistics shipyard.py convoy\\*.py
- IF "%PYTHON_VERSION%"=="3.7" (
  flake8 --statistics cascade\\*.py cargo\\*.py
  )
